#!/usr/bin/env python3

import json, requests
from pprint import pprint
import sys

r = requests.get(url='http://pokeapi.co/api/v1/pokemon/' + sys.argv[1])
data = json.loads(r.text)

#pprin(data)
print("Name: " + data["name"])
print("Speed: " + str(data["speed"]))
print("Defense: " + str(data["defense"]))
print("Attack: " + str(data["attack"]))
print("Height: " + str(data["height"]))
for move in data["moves"]:
  print(move["name"], end=", ")
